package chart

const (
	// XXX: Update this when defaultHelpers changes in https://github.com/helm/helm/blob/main/pkg/chartutil/create.go.
	NameFormat               = "%s.name"
	FullNameFormat           = "%s.fullname"
	ChartFormat              = "%s.chart"
	CommonLabelsFormat       = "%s.labels"
	SelectorLabelsFormat     = "%s.selectorLabels"
	ServiceAccountNameFormat = "%s.serviceAccountName"
)

const (
	Header = "# Generated by [Kustohelmize](https://github.com/yeahdongcn/kustohelmize)\n"
)
